//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_Cart = new HashSet<tbl_Cart>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public string Warranty { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> SoldItems { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImagePath { get; set; }
        public string DisplayType { get; set; }
        public string DisplaySize { get; set; }
        public string Resolution { get; set; }
        public string SelfieCamera { get; set; }
        public string MainCamera { get; set; }
        public string ROM { get; set; }
        public string RAM { get; set; }
        public string OperatingSystem { get; set; }
        public string Chipset { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public string Weight { get; set; }
        public string Color { get; set; }
        public string Dimension { get; set; }
        public string SIM { get; set; }
        public string WLAN { get; set; }
        public string Bluetooth { get; set; }
        public string GPS { get; set; }
        public string USB { get; set; }
        public string BatteryType { get; set; }
        public string Sensors { get; set; }
        public string Video { get; set; }
        public string NetworkTechnology { get; set; }
        public Nullable<int> ReleaseYear { get; set; }
        public Nullable<int> Ratings { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
    }
}
